trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Test
  jobs:
  - job: RunTestkube
    steps:
      - task: SetupTestkube@1
        inputs:
          organization: '$(TK_ORG_ID)'
          environment: '$(TK_ENV_ID)'
          token: '$(TK_API_TOKEN)'
      - script: |
          git clone https://github.com/techmaharaj/testkube-GH.git
          cd testkube-GH/k6
          testkube create test --name k6-test --type k6/script --update -f testkube.js
          testkube run test k6-test
        displayName: Run Testkube Test
