name: Running Testkube Tests.
on:
  push:
    branches:
      - main
jobs:
  test_worflow:
    name: test workflow for local minikube.
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get pods -A
     
