name: Running Testkube Tests.
on:
  push:
    branches:
      - main
jobs:
   job_1:
     name: test workflow for AWS
     runs-on: ubuntu-latest
     steps:
     - name: AWS cli install action
       uses: chrislennon/action-aws-cli@1.1
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-west-2
     - name: kubeconfig
       run: |
         aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
       
