name: Running tests with Testkube
on:
  pull_request:
env:
  CLUSTER_NAME: scrumptious-hideout-1700805231
  AWS_REGION: us-west-2
 
jobs:
   job_1:
    name: Testkube K6 Workflow For EKS Cluster
    runs-on: ubuntu-latest
    outputs:
      outpu1: ${{ steps.get_output.outputs.status }}
    steps:
    - name: Configure AWS cluster
      uses: kubeshop/setup-testkube@v1
      with:
        organization: ${{ secrets.TESTKUBE_ORG_ID }}
        environment: ${{ secrets.TESTKUBE_ENV_ID }}
        token: ${{ secrets.TESTKUBE_API_TOKEN }}
    - run: |
        testkube create test --name k6-kubeshop-test --type k6/script --test-content-type git-file --git-uri https://github.com/techmaharaj/testkube-GH.git --git-branch main --git-path k6/testkube.js
        testkube run test k6-kubeshop-test -f
