name: Running Testkube Tests.
on:
  push:
    branches:
      - main
jobs:
  test_worflow:
    name: test workflow for local minikube.
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Extract IP Address
        id: extract-ip-address
        run: |
          # Read the first line of ip.txt into a variable
          IP_ADDRESS=$(head -n 1 ip.txt)
          echo "Extracted IP Address: $IP_ADDRESS"
          echo "IP_ADDRESS=$IP_ADDRESS" >> $GITHUB_ENV
      - name: Print IP Address
        run: echo "The extracted IP address is $IP_ADDRESS"

      - name: Run test
        uses: kubeshop/testkube-run-action@v1
        with:
        # Instance
          organization: ${{ secrets.TkOrganization }}
          environment: ${{ secrets.TkEnvironment }}
          token: ${{ secrets.TkToken }}
          url: https://api.testkube.dev/
          test: curl-url-test
          variables: |
            IP="${{ steps.test_workflow.outputs.IP_ADDRESS }}"
