name: Running tests with Testkube
on:
  pull_request:
env:
  CLUSTER_NAME: scrumptious-hideout-1700805231
  AWS_REGION: us-west-2
 
jobs:
   job_1:
    name: test workflow for AWS
    runs-on: ubuntu-latest
    outputs:
      outpu1: ${{ steps.get_output.outputs.status }}
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
    - name: Create & Run Test
      uses: kubeshop/setup-testkube@v1
      env:
        KUBECONFIG: ${{ github.workspace }}/config
    - run: |
        testkube create test --name k6-amazon-test --type k6/script --test-content-type git-file --git-uri https://github.com/techmaharaj/testkube-GH.git --git-branch main --git-path k6/testkube.js
        testkube run test k6-amazon-test -f
