name: Running Testkube Tests.
on:
  push:
    branches:
      - main
env:
  CLUSTER_NAME: ferocious-badger-1695294076
  AWS_REGION: us-west-2
  
jobs:
   job_1:
     name: test workflow for AWS
     runs-on: ubuntu-latest
     steps:
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-west-2
     - name: kubeconfig
       run: |
         aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
     - name: Copy k8s config file
       run: cp /home/runner/.kube/config ${{ github.workspace }}
     - name: Create test
       uses: kubeshop/testkube-docker-action@v1
       env:
         KUBECONFIG: ${{ github.workspace }}/config
       with:
         command: create
         resource: test
         namespace: testkube
         parameters: "--git-uri https://github.com/infracloudio/testkube-django-app.git --git-path myproject/examples/ --type ginkgo/test --name testkube-github-action --git-branch master"
     - name: Run test
       id: run_test
       uses: kubeshop/testkube-docker-action@v1
       env:
         KUBECONFIG: ${{ github.workspace }}/config
       with:
         command: run
         resource: test
         namespace: testkube
         parameters: testkube-github-action
     - name: Sleep for 10 seconds
       run: sleep 10s
       shell: bash
     - name: Get Test Results
       id: get_test_results
       uses: kubeshop/testkube-docker-action@v1
       env:
         KUBECONFIG: ${{ github.workspace }}/config
       with:
         command: get
         resource: execution
         namespace: testkube
         parameters: testkube-github-action

